In [42]:
import numpy as np
from datetime import date, timedelta

## 1. Create a 3x3x3 array with random values

In [43]:
array = np.random.rand(3,3,3)
array

array([[[0.72887564, 0.11568175, 0.1600774 ],
        [0.81318131, 0.59604584, 0.44187923],
        [0.94409204, 0.36019537, 0.69755543]],

       [[0.33435141, 0.8233088 , 0.57424015],
        [0.94256699, 0.66278643, 0.36587708],
        [0.22489587, 0.58195449, 0.84553974]],

       [[0.82114734, 0.90551376, 0.69736391],
        [0.53547085, 0.9229461 , 0.14594354],
        [0.91804166, 0.33463769, 0.96754805]]])

## 2. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [44]:
array_2 = np.diag(np.arange(4) + 1, k = -1)
array_2

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

## 3. Create a 8x8 matrix and fill it with a checkerboard pattern

In [45]:
array_3 = np.tile(np.array([[0,1],[1,0]]), (4,4))
array_3

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

## 4. Normalize a 5x5 random matrix¶

In [46]:
array_4 = np.random.random((5,5))
array_4 = (array_4 - np.mean (array_4)) / (np.std (array_4))
array_4

array([[-0.87600534, -0.22188464, -0.19978864,  1.14030405,  0.11088377],
       [ 0.05319324,  1.42542844,  1.2266301 ,  0.23822312, -0.24413114],
       [ 1.28949045, -0.52875547, -0.15019524,  1.4024413 , -1.11721548],
       [-1.99397485,  0.04617708,  0.83839197, -1.96425373,  0.88882475],
       [ 0.24495667,  0.77483138, -1.79192937,  0.26078539, -0.85242781]])

## 5. How to find common values between two arrays

In [47]:
A = np.random.randint(0,8,8)
B = np.random.randint(0,10,10)
np.intersect1d(A,B)

array([1, 3, 5, 7])

## 6. How to get the dates of yesterday, today and tomorrow?

In [48]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)
print( "Yetserdy  -", yesterday)
print("Today  -" , today)
print("Tomorrow  -", tomorrow)

Yetserdy  - 2020-07-27
Today  - 2020-07-28
Tomorrow  - 2020-07-29


## 7. Consider two random array A and B, check if they are equal

In [49]:
A = np.random.rand(3,3)
B = np.random.rand(3,3)
Equality = np.array_equal(A, B)
print(f'A:\n{A}\n\n')
print(f'B:\n{B}\n\n')
print(f'Are they equal?: {Equality}')

A:
[[0.3787077  0.14153548 0.25573794]
 [0.0140595  0.09358655 0.98122147]
 [0.73005051 0.96495406 0.28489957]]


B:
[[0.18787296 0.94033415 0.72078697]
 [0.51854774 0.03641256 0.44604823]
 [0.98038832 0.11151725 0.42982443]]


Are they equal?: False


## 8. Create random vector of size 10 and replace the maximum value by 0

In [50]:
arr = np.random.rand(10)
arr[arr.argmax()] = 0
arr

array([0.        , 0.35045393, 0.33479834, 0.78629509, 0.49757437,
       0.14349704, 0.32438177, 0.44346139, 0.59471114, 0.09874469])

## 9. How to print all the values of an array?

In [51]:
arr = np.ones((10, 10))
print(arr)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


## 10. Subtract the mean of each row of a matrix

In [52]:

array = np.random.rand(3,3)
array_mean = array - array.mean(axis=1, keepdims=True)

array_mean

array([[-0.13400499,  0.34454849, -0.21054351],
       [-0.14739798, -0.11381503,  0.26121301],
       [ 0.35850435, -0.30894863, -0.04955572]])

## 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?


In [53]:

arr1 = np.ones(5)
arr2 = np.random.randint(0, len(arr1), 10)
arr1 += np.bincount(arr2, minlength = len(arr1))
arr1

array([2., 3., 2., 4., 4.])

## 12. How to get the diagonal of a dot product?

In [54]:
arr1 = np.random.randint(0,10,(3,3))
arr2 = np.random.randint(0,10,(3,3))

np.einsum("ij,ji->i", arr1, arr2)

array([ 35, 107,  91])

## 13. How to find the most frequent value in an array?

In [55]:
arr = np.random.randint(0,10,20)
print(arr)
max(set(arr), key = list(arr).count)

[7 4 7 4 2 4 7 2 7 0 1 9 5 7 0 4 3 7 5 2]


7

## 14. How to get the n largest values of an array

In [56]:
arr = np.random.randint(0,10,50)
np.bincount(arr).argmax()

1

## 15. How to create a record array from a regular array?

In [57]:
arr = np.array([("Science", 40, 90),
                 ("Maths", 100, 79),
             ("English", 75, 81)])

print(arr)
print("\nRECORD ARRAY")
record = np.core.records.fromarrays(arr.T,
                              names='col1, col2, col3',
                              formats = 'S80, f8, i8')
record

[['Science' '40' '90']
 ['Maths' '100' '79']
 ['English' '75' '81']]

RECORD ARRAY


rec.array([(b'Science',  40., 90), (b'Maths', 100., 79),
           (b'English',  75., 81)],
          dtype=[('col1', 'S80'), ('col2', '<f8'), ('col3', '<i8')])